server:
    port: 8067
spring:
    data:
        neo4j:
            password: 123456
            uri: bolt://localhost
            username: neo4j
#
#eureka:         #tells about the Eureka server details and its refresh time
#    instance:
#        leaseRenewalIntervalInSeconds: 1
#        leaseExpirationDurationInSeconds: 2
#    client:
#        serviceUrl:
#            defaultZone: http://127.0.0.1:8066/eureka/
#        healthcheck:
#            enabled: true
#        lease:
#            duration: 5
management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

