producer:
    port: 172.23.239.133
server:
    port: 8094

local:
    file:
        path: ./src/main/resources/Doc
eureka:         #tells about the Eureka server details and its refresh time
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8066/eureka/
        healthcheck:
            enabled: true
        lease:
            duration: 5
management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.